version: "3.8"
services:
    beService:
        container_name: beService
        volumes:
            -   ./:/app
        ports:
            - "4000:4000"
        image: node:slim
        command: bash -c "cd /app && npm install && npm run start"
        networks:
            - network

networks:
    network:
        driver: bridge

volumes:
    database:
        driver: local
